name: automatisation

on:
  push:
    branches-ignore:
    - ga-ignore-
  pull_request:
    branches-ignore:
    - ga-ignore-
env:
      MIRROR_URL: https://github.com/EpitechPromo2026/B-DOP-200-COT-2-1-chocolatine-alberick.mahoussi.git
      EXECUTABLES: lib/my/libmy.a
  
jobs:
    check_reposistory_cleanliness:
      name: check_cleanliness
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - id: check_reposistory_cleanliness
          run: |
            BAD_FILE=($(find . -wholename "*/tmp/*" -name "*#" -o -name "#*" -o -iname "*pain_au_chocolat*" -o -name "*.o" -o -name "*.a" -o -name "*~" -o -name "~*" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" ))
            for FILES in ${BAD_FILES[#]}; do
            echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE./}"; done
            if [[ -n $r_file ]]
            then
              exit 1
            else
            echo No unwnanted file detected
            fi
            
    verification_of_compilation:
      needs: [check_reposistory_cleanliness]
      name: check if file can compile
      runs-on:  ubuntu-latest
      container:
        image: epitechcontent/epitest-docker:latest
      steps:
        - uses: actions/checkout@v3
        - id: check_program_compilation
          run: make
          timeout-minutes: 2
        - run: make clean
        
    test_file_working:
      needs: [verification_of_compilation]
      name: test run
      runs-on: ubuntu-latest
      container:
        image: epitechcontent/epitest-docker:latest
      steps:
        - uses: action/checkout@v3
        - id: run_test
          run: make test_run
          timeout-minutes: 2
          
    mirrorinh_push:
      needs: [test_file_working]
      if: ${{ github.event_name == 'push' }}
      name: "pushing_in_mirror"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: pixta-dev/reposistory-mirroring-action@v1
          with:
            target_repo_url:
              ${{ env.MIRROR_URL }}
    
          
      
        
        
  
